import type { ProvinceSchema } from "./types";

export const newBrunswickSchema: ProvinceSchema = {
  provinceSlug: "new-brunswick",
  provinceName: "New Brunswick",
  formTitle: "New Brunswick Driver Medical Fitness Report",
  version: "1.0.0",
  metadata: {
    estimatedMinutes: 8,
    formCode: "DL-1",
    regulatoryBody: "Service New Brunswick",
  },
  fields: [
    // --- Personal Information ---
    {
      id: "full_name",
      type: "text",
      section: "Personal Information",
      label: "What is your full legal name?",
      placeholder: "First and last name",
      validation: [{ type: "required", message: "Your full name is required" }],
    },
    {
      id: "date_of_birth",
      type: "date",
      section: "Personal Information",
      label: "What is your date of birth?",
      validation: [{ type: "required", message: "Date of birth is required" }],
    },
    {
      id: "address",
      type: "text",
      section: "Personal Information",
      label: "What is your mailing address?",
      placeholder: "Street, city, province, postal code",
      validation: [{ type: "required", message: "Address is required" }],
    },
    {
      id: "phone",
      type: "text",
      section: "Personal Information",
      label: "What is your phone number?",
      placeholder: "(506) 000-0000",
      validation: [{ type: "required", message: "Phone number is required" }],
    },
    {
      id: "licence_number",
      type: "text",
      section: "Licence Details",
      label: "What is your driver's licence number?",
      placeholder: "Enter your licence number",
      validation: [{ type: "required", message: "Licence number is required" }],
    },
    {
      id: "licence_class",
      type: "option-select",
      section: "Licence Details",
      label: "What class of licence are you applying for?",
      options: [
        { label: "Class 1", value: "class_1", description: "Semi-trailer trucks" },
        { label: "Class 2", value: "class_2", description: "Buses" },
        { label: "Class 3", value: "class_3", description: "Large trucks" },
        { label: "Class 4", value: "class_4", description: "Ambulances, small buses" },
      ],
      validation: [{ type: "required", message: "Licence class is required" }],
    },

    // --- Medical History ---
    {
      id: "has_seizures",
      type: "yes-no",
      section: "Medical History",
      label: "Have you ever had seizures, epilepsy, or loss of consciousness?",
    },
    {
      id: "seizures_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe your seizure or loss of consciousness history.",
      placeholder: "Include dates, frequency, treatment, and current status",
      conditions: [{ field: "has_seizures", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },
    {
      id: "has_diabetes",
      type: "yes-no",
      section: "Medical History",
      label: "Do you have diabetes?",
    },
    {
      id: "diabetes_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe your diabetes management.",
      placeholder: "Include type, medications (insulin?), and how well controlled",
      conditions: [{ field: "has_diabetes", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },
    {
      id: "has_heart_condition",
      type: "yes-no",
      section: "Medical History",
      label: "Do you have any heart or cardiovascular condition?",
    },
    {
      id: "heart_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe your heart or cardiovascular condition.",
      placeholder: "Include diagnosis, treatment, and current status",
      conditions: [{ field: "has_heart_condition", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },
    {
      id: "has_vision_problems",
      type: "yes-no",
      section: "Medical History",
      label: "Do you have any vision problems that are not corrected by glasses or contacts?",
    },
    {
      id: "vision_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe your vision problems.",
      placeholder: "Include diagnosis and any treatment",
      conditions: [{ field: "has_vision_problems", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },
    {
      id: "has_hearing_loss",
      type: "yes-no",
      section: "Medical History",
      label: "Do you have significant hearing loss?",
    },
    {
      id: "hearing_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe your hearing condition.",
      placeholder: "Include whether you use hearing aids",
      conditions: [{ field: "has_hearing_loss", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },
    {
      id: "has_mental_health",
      type: "yes-no",
      section: "Medical History",
      label: "Do you have any psychiatric or mental health conditions?",
    },
    {
      id: "mental_health_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe your mental health condition.",
      placeholder: "Include diagnosis, medication, and treatment",
      conditions: [{ field: "has_mental_health", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },
    {
      id: "has_substance_use",
      type: "yes-no",
      section: "Medical History",
      label: "Do you have a history of substance use or dependence?",
    },
    {
      id: "substance_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe your substance use history.",
      placeholder: "Include substances, treatment, and recovery status",
      conditions: [{ field: "has_substance_use", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },
    {
      id: "has_sleep_disorder",
      type: "yes-no",
      section: "Medical History",
      label: "Do you have a sleep disorder such as sleep apnea?",
    },
    {
      id: "sleep_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe your sleep disorder.",
      placeholder: "Include diagnosis, treatment (CPAP?), and compliance",
      conditions: [{ field: "has_sleep_disorder", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },
    {
      id: "has_musculoskeletal",
      type: "yes-no",
      section: "Medical History",
      label: "Do you have any musculoskeletal conditions or limb impairments?",
    },
    {
      id: "musculoskeletal_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe your musculoskeletal condition.",
      placeholder: "Include diagnosis and any functional limitations",
      conditions: [{ field: "has_musculoskeletal", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },
    {
      id: "has_other_conditions",
      type: "yes-no",
      section: "Medical History",
      label: "Do you have any other medical conditions that may affect your ability to drive safely?",
    },
    {
      id: "other_conditions_details",
      type: "textarea",
      section: "Medical History",
      label: "Please describe any other medical conditions.",
      placeholder: "Include diagnosis, treatment, and current status",
      conditions: [{ field: "has_other_conditions", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please provide details" }],
    },

    // --- Medications ---
    {
      id: "takes_medications",
      type: "yes-no",
      section: "Medications",
      label: "Are you currently taking any medications?",
    },
    {
      id: "medications_list",
      type: "textarea",
      section: "Medications",
      label: "Please list all medications you are currently taking.",
      placeholder: "Include name, dosage, and frequency for each medication",
      conditions: [{ field: "takes_medications", operator: "eq", value: "yes" }],
      validation: [{ type: "required", message: "Please list your medications" }],
    },

    // --- Declaration ---
    {
      id: "declaration",
      type: "checkbox",
      section: "Declaration",
      label: "I confirm that the information provided is accurate and complete to the best of my knowledge.",
      validation: [{ type: "required", message: "You must confirm this declaration to proceed" }],
    },
  ],
};
